# Generated by Django 3.2.16 on 2022-12-09 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.PositiveSmallIntegerField(default=0, verbose_name='series')),
                ('number', models.PositiveSmallIntegerField(default=0, verbose_name='number')),
                ('release_date', models.DateTimeField(auto_now_add=True, verbose_name='release at')),
                ('ending_date', models.DateTimeField(verbose_name='terminates at')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DEACTIVATED', 'Deactivated'), ('OVERDUE', 'Overdue')], default='DEACTIVATED', max_length=11, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='purchase amout')),
                ('purchase_date', models.DateTimeField(verbose_name='purchase date')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='storage.card')),
            ],
        ),
    ]
